use std::env;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: {} <CellName> [supported_signals...]", args[0]);
        std::process::exit(1);
    }

    let cell_name = &args[1];
    let supported_signals: Vec<&String> = args.iter().skip(2).collect();
    let signals_refs: Vec<&str> = supported_signals.iter().map(|s| s.as_str()).collect();

    println!("// Auto-generated by cell_codegen");
    println!("use axiom_kernel::cell::{{DynCell, DynHandleCell, RuntimeCellHandle}};");
    println!("use axiom_kernel::context::CellContext;");
    println!("use axiom_kernel::id::CellId;");
    println!("use axiom_kernel::layer::Layer;");
    println!("use axiom_kernel::signal::SignalEnvelope;");
    println!();
    println!("pub struct {};", cell_name);
    println!();
    println!("impl DynCell for {} {{", cell_name);
    println!("    fn id(&self) -> &CellId {{");
    println!("        use std::sync::LazyLock;");
    println!(
        "        static ID: LazyLock<CellId> = LazyLock::new(|| CellId::new(\"{}-cell\"));",
        cell_name.to_lowercase()
    );
    println!("        &ID");
    println!("    }}");
    println!("    fn layer(&self) -> Layer {{");
    println!("        Layer::Exec");
    println!("    }}");
    if !signals_refs.is_empty() {
        println!("    fn supported_signals(&self) -> &[&'static str] {{");
        println!(
            "        &[{}]",
            signals_refs
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        );
        println!("    }}");
    }
    println!("    fn as_any(&self) -> &dyn std::any::Any {{");
    println!("        self");
    println!("    }}");
    println!("    fn as_any_mut(&mut self) -> &mut dyn std::any::Any {{");
    println!("        self");
    println!("    }}");
    println!("}}");
    println!();
    println!("impl DynHandleCell for {} {{", cell_name);
    println!("    fn handle_dyn<'a>(");
    println!("        &'a mut self,");
    println!("        _env: SignalEnvelope,");
    println!("        _ctx: &'a mut CellContext<'a>,");
    println!("    ) -> BoxHandleFuture<'a> {{");
    println!("        Box::pin(async move {{");
    println!("            (Ok(()), Vec::new(), Vec::new())");
    println!("        }})");
    println!("    }}");
    println!("}}");
    println!();
    println!("// Example registration:");
    println!("// let cell = RuntimeCellHandle::new(Box::new({}));", cell_name);
    println!("// rt.register_cell(");
    println!("//     CellRegistration::new(CellId::new(\"{}-cell\"), Layer::Exec)", cell_name.to_lowercase());
    println!("//         .with_cell(cell)");
    if !signals_refs.is_empty() {
        println!(
            "//         .with_supported_signals(vec![{}])",
            signals_refs
                .iter()
                .map(|s| format!("\"{}\"", s))
                .collect::<Vec<_>>()
                .join(", ")
        );
    }
    println!("// )");
}
