use anyhow::{Context, Result};
use clap::{Arg, ArgAction, Command};
use std::path::PathBuf;
use std::process::Command as ProcessCommand;

fn main() -> Result<()> {
    let matches = Command::new("xtask")
        .about("Architecture governance task runner")
        .subcommand_required(true)
        .arg_required_else_help(true)
        .subcommand(
            Command::new("gatecheck")
                .about("Run architecture gate check")
                .arg(
                    Arg::new("format")
                        .long("format")
                        .short('f')
                        .value_name("FORMAT")
                        .default_value("text")
                        .help("Output format: text or json"),
                )
                .arg(
                    Arg::new("output")
                        .long("output")
                        .short('o')
                        .value_name("FILE")
                        .help("Write report to file"),
                )
                .arg(
                    Arg::new("strict")
                        .long("strict")
                        .action(ArgAction::SetTrue)
                        .help("Exit with error if violations found"),
                )
                .arg(
                    Arg::new("list-crates")
                        .long("list-crates")
                        .action(ArgAction::SetTrue)
                        .help("List all registered crates"),
                ),
        )
        .subcommand(
            Command::new("state")
                .about("Generate architecture state snapshot")
                .arg(
                    Arg::new("output")
                        .long("output")
                        .short('o')
                        .value_name("FILE")
                        .default_value(".axiom/state.toml")
                        .help("Output path for state file"),
                ),
        )
        .get_matches();

    match matches.subcommand() {
        Some(("gatecheck", args)) => {
            let format = args
                .get_one::<String>("format")
                .expect("format is required");
            let output = args.get_one::<String>("output").map(|s| s.as_str());
            let strict = args.get_flag("strict");
            let list_crates = args.get_flag("list-crates");

            let mut cmd = ProcessCommand::new("cargo");
            cmd.args(["run", "--bin", "archcheck", "--"]);

            if list_crates {
                cmd.arg("--list-crates");
            }

            if let Some(output) = output {
                cmd.args(["--format", format, "--output", output]);
            } else {
                cmd.args(["--format", format]);
            }

            let status = cmd.status().context("running archcheck")?;

            if !status.success() {
                if strict {
                    std::process::exit(1);
                } else {
                    eprintln!("warning: architecture violations found (non-strict mode, not failing build)");
                }
            }

            Ok(())
        }
        Some(("state", args)) => {
            let output = args
                .get_one::<String>("output")
                .expect("output is required");
            let state_path = PathBuf::from(output);

            let arch_path = std::env::var("AXIOM_ARCHITECTURE_TOML")
                .unwrap_or_else(|_| ".axiom/architecture.toml".to_string());
            let arch_toml = std::fs::read_to_string(&arch_path)
                .with_context(|| format!("reading {}", arch_path))?;
            let parsed: toml::Value = toml::from_str(&arch_toml)
                .with_context(|| format!("parsing {}", arch_path))?;

            let mut state = String::new();
            state.push_str("# Auto-generated by `cargo xtask state`. DO NOT EDIT.\n");
            state.push_str(&format!("# Source: {}\n\n", arch_path));
            state.push_str("[state]\n");
            state.push_str("generated_by = \"xtask state\"\n\n");

            if let Some(crate_layers) = parsed.get("crate-layers").and_then(|v| v.as_table()) {
                state.push_str("[crates]\n");
                for (name, layer) in crate_layers {
                    if let Some(l) = layer.as_integer() {
                        state.push_str(&format!("{} = {}\n", name, l));
                    }
                }
            }

            std::fs::write(&state_path, state).context("writing state file")?;
            println!("State written to {}", state_path.display());
            Ok(())
        }
        _ => unreachable!(),
    }
}
